### ISSUE TITLE
[CL] MySQL Dockerfile 작성

### ISSUE THREAD

**Issue by yubin425** [100-hours-a-week/20-real-cloud#114]
# 🌍 개요

## 🔄 CI/CD 작업 리스트

- [x] docker-compose.yml 작성

**Comment by yubin425** [comment]
```
version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: my-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw     # root 계정 비번
      MYSQL_DATABASE: app_db                # 기본 DB명
      MYSQL_USER: app_user                  # 사용자 계정
      MYSQL_PASSWORD: app_pw                # 사용자 계정 비번
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql               # DB 데이터 영구 저장
      - ./my.cnf:/etc/mysql/conf.d/my.cnf:ro      # MySQL 커스텀 설정(선택)

  redis:
    image: redis:7.2
    container_name: my-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data                        # Redis 데이터 영구 저장(옵션)

volumes:
  mysql_data:
  redis_data:
```

그냥 위와 같이 redis + mysql 공식 이미지 사용해서 docker compose up -d 로 올리면 될 것 같습니다.
