### ISSUE TITLE
[Troubleshooting]  2025-06-23 - k8s kubeadm에서 ALB Controller 작동 실패

### ISSUE THREAD

**Issue by yubin425** [100-hours-a-week/20-real-cloud#218]
# 2025-06-23 k8s kubeadm에서 ALB Controller 작동 실패

### 🐞 에러 내용

* Ingress 리소스에 적절한 annotation을 적용했음에도 ALB가 생성되지 않음

### 🔍 원인 분석

* `kubernetes.io/ingress.class`, `alb.ingress.kubernetes.io/scheme` 등의 annotation이 ALB Controller 버전마다 다름
* 공식 문서, 예제 간 불일치로 인해 구버전/신버전 섞이면 미작동

### ✅ 해결 방법

* 공식 GitHub 리포지토리의 버전과 맞는 annotation을 사용

```yaml
metadata:
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    kubernetes.io/ingress.class: alb
```

### 회고

* 문서 불일치와 버전 호환성 이슈로 디버깅에 시간이 과도하게 소모됨
* **시간에 맞추는 것도 중요하기 때문에**, 구조적으로 안정적인 EKS 환경으로 전환을 고려

---

### 🐞 에러 내용

* Ingress, Role, ServiceAccount 리소스 적용 시 "unrecognized field" 또는 "deprecated" 경고 발생

### 🔍 원인 분석

* Kubernetes 1.22 이상부터 `networking.k8s.io/v1beta1` → `v1`로 변경됨
* 오래된 튜토리얼을 참조할 경우 버전 불일치 발생

### ✅ 해결 방법

```yaml
# 변경 전 (오류)
apiVersion: networking.k8s.io/v1beta1
kind: Ingress

# 변경 후
apiVersion: networking.k8s.io/v1
kind: Ingress
```

### 회고

* Kubernetes 리소스 정의 시 항상 클러스터 버전에 맞는 schema를 확인해야 함

---

### 🐞 에러 내용

* `aws-load-balancer-controller` Pod CrashLoopBackOff
* ALB 생성 실패

### 🔍 원인 분석

* ALB Controller는 EKS 환경에서의 IRSA, VPC, cluster name 등을 자동 추론함
* kubeadm 환경에서는 수동으로 모두 입력해야 하며, IAM 연동 어려움

### ✅ 해결 방법

* Helm values.yaml에 필수값 명시

```yaml
helm:
  values: |
    clusterName: my-kubeadm-cluster
    region: ap-northeast-2
    vpcId: vpc-123abc
    serviceAccount:
      create: false
      name: aws-load-balancer-controller
```

### 회고

* **kubeadm 환경은 ALB Controller와의 구조적 호환성이 낮음**
* 시간과 안정성을 고려해 EKS로의 마이그레이션 결정

---

### 🐞 에러 내용

* ArgoCD Application에서 repo-server 통신 오류 (`i/o timeout`)
* Ingress 요청이 백엔드로 전달되지 않음

### 🔍 원인 분석

* `NetworkPolicy`가 ingress/egress 조건을 명시하지 않아 default deny 상태

### ✅ 해결 방법

```yaml
apiVersion: networking.k8s.io/v1beta3
kind: NetworkPolicy
spec:
  podSelector:
    matchLabels:
      app: argocd-repo-server
  ingress:
  - from:
    - namespaceSelector: {}  # 모든 네임스페이스 허용
```

### 회고

* 통신 구조를 이해하지 못하면 디버깅이 오래 걸림
* NetworkPolicy는 구성 초기에 신중하게 설계 필요

---

### 🐞 에러 내용

* `lookup argocd-repo-server: i/o timeout`
* ALB 또는 ArgoCD 리소스가 내부 DNS를 통해 서비스 주소를 해석하지 못함

### 🔍 원인 분석

* CoreDNS가 crash 상태이거나 네트워크 정책/iptables로 요청 차단됨

### ✅ 해결 방법

```bash
kubectl delete pod -n kube-system -l k8s-app=kube-dns
# 또는
kubectl rollout restart deployment coredns -n kube-system
```

### 회고

* CoreDNS는 K8s 서비스 디스커버리의 핵심이며, 장애 시 전체 통신 불능 발생
* 문제 발생 시 즉각적인 재시작 및 로그 확인이 중요함

---

## 종합 회고

* ALB Controller는 kubeadm 환경과의 호환성이 떨어지고 설정이 복잡함
* NetworkPolicy와 CoreDNS 문제 등도 인프라에 치명적 영향을 미침
* **시간에 맞추는 것도 중요하기 때문에**, 지속적인 디버깅보다는 구조적으로 안정된 **EKS로의 마이그레이션**을 선택함
* EKS에서는 IAM 연동, ALB Controller 설치, Ingress 처리 등이 표준화되어 있어 운영 효율성과 신뢰성이 높음
