### ISSUE TITLE
[Troubleshooting] 2025-06-24 argocd 도메인 접속 불가 및 무한 리디렉션

### ISSUE THREAD

**Issue by yubin425** [100-hours-a-week/20-real-cloud#220]
# 2025-06-24   argocd 도메인 접속 불가 및 무한 리디렉션

## 🐞 에러 내용

* `http://도메인` 요청 시 307 리디렉션 발생 후 `https://도메인`으로 이동
* 최종적으로 **"페이지가 작동하지 않습니다. 리디렉션 횟수가 너무 많습니다."** 오류 발생
* 또는 `ERR_CONNECTION_TIMED_OUT`, `SSL Handshake Failed`, 502 Bad Gateway 등 다양한 증상 발생

### 1. Ingress Pod가 하나의 Node에만 배포되어 있었음

* `externalTrafficPolicy: Local` 설정 상태에서 **Ingress Pod가 없는 Node**로 ALB 트래픽이 전달되면 응답 불가
* ALB 타겟 그룹에는 여러 Node가 등록되어 있었지만, 실제 Ingress Pod는 1개 Node에만 존재 → 헬스체크 실패 및 ALB 503

### 2. ALB 헬스체크 실패

* 기본적으로 **NGINX Ingress Controller는 `/healthz` 경로에 대해 10254 포트**에서만 응답
* 하지만 ALB는 NodePort(예: 32080)로만 헬스체크를 수행 → **헬스체크 실패**
* 대안으로 NGINX가 80포트에서 `/healthz` 응답을 하도록 설정 필요

### 3. HTTPS 리디렉션 무한 루프

* ALB는 HTTPS로 트래픽을 전달하나, Ingress 설정은 **HTTP 처리**
* ArgoCD는 내부적으로 HTTP 요청이면 HTTPS로 리디렉션
* 하지만 **X-Forwarded-Proto** 헤더가 전달되지 않아, ArgoCD가 계속 리디렉션 유발

### 4. Ingress 설정 미비

* `nginx.ingress.kubernetes.io/backend-protocol`, `ssl-redirect`, `x-forwarded-prefix` 등 설정 누락

### 5. ArgoCD 서버 설정 미비

* `--insecure` 옵션이 없어 HTTPS 없이 접근 시 ArgoCD 내부 리디렉션 유발

### 1. Ingress Pod와 ALB 타겟 Node 정합성 확보

* `externalTrafficPolicy: Local`일 경우, **Ingress Pod가 배포된 Node만 ALB 타겟 그룹에 등록**

#### 방법 1: dummy nginx로 `/healthz` 응답

```yaml
command: ["/bin/sh", "-c"]
args:
  - echo -e "HTTP/1.1 200 OK\n\nok" > /usr/share/nginx/html/healthz.html && nginx -g 'daemon off;'
```

→ NGINX가 80포트에서 `/healthz` 응답하도록 구성

#### 방법 2: Helm 설정으로 Ingress Controller가 80포트에서 `/healthz` 응답

```yaml
controller:
  healthz:
    port:
      enabled: true
```

→ 이후 dummy nginx 제거 가능

### 3. Ingress 설정 보완

```yaml
annotations:
  nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
  nginx.ingress.kubernetes.io/ssl-redirect: "false"
  nginx.ingress.kubernetes.io/x-forwarded-prefix: "/"
```

### 4. ArgoCD 서버에 `--insecure` 옵션 추가

```yaml
args:
  - --insecure
```

```bash
kubectl rollout restart deployment argocd-server -n argocd
```

## 🌀 회고

* ALB → NodePort → Ingress → ArgoCD 흐름에서 **프로토콜 불일치**와 **헬스체크**가 주요 장애 요인
* `externalTrafficPolicy: Local` 사용 시에는 Node 선정과 헬스체크 경로 모두 정밀하게 설계해야 함
* NGINX Ingress의 `/healthz`가 기본적으로 10254 포트임을 몰랐던 것이 핵심 원인 중 하나
* Helm 설정으로 `controller.healthz.port.enabled: true`를 넣으면 80 포트에서도 응답 가능 → **dummy 서비스 제거 가능**
* ArgoCD는 TLS가 필수인 서비스로, 프록시(TLS termination) 사용 시 반드시 `--insecure` 또는 헤더 처리 필요
* GitOps 환경에서는 webhook admission이 오류를 유발할 수 있으므로 **controller.admissionWebhooks.enabled: false**도 고려 필요
